### ISSUE TITLE
Inconsistent usage of "roll." vs "roll+0."

### ISSUE THREAD

**Issue by SRabbelier** [Sagelt/beyond#5]
Example:

- When you have leverage on a GM Character and push them to do what you want, roll.
- When you consult your accumulated knowledge about something, roll+0.

**Comment by Sagelt** [comment]
Yeah, this was a side effect of me deciding during writing to spell it out. Likely end state here is that in the text it's inlined like this, and that on character sheets it just says "roll" with a box by the title for the bonus with the starting bonus greyed in.
